# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - 'go mod tidy -v'
    - 'go-licenses save ./cmd/wholidisuka/ --force --save_path ./licenses/'

builds:
  - main: './cmd/wholidisuka/'
    env:
      - 'CGO_ENABLED=0'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    format: 'tar.xz'
    format_overrides:
      - goos: 'windows'
        format: 'zip'
    files:
      - './LICENSE'
      - './README.md'
      - './licenses/**/*'

checksum:
  name_template: 'checksums.txt'
